# Generated by Django 4.1 on 2022-08-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_category_option_order_user_verified_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='night_owl/product'),
        ),
    ]
