# Generated by Django 4.1 on 2022-08-11 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_amount',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
