# Generated by Django 4.1 on 2022-08-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='can_destroy',
            field=models.BooleanField(default=True),
        ),
    ]
