# Generated by Django 4.1 on 2022-08-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_shipper_order_order_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
