# Generated by Django 4.1 on 2022-08-16 12:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_order_can_destroy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='product_option',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='order_detail',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_voucher',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='shipping_id',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='status',
        ),
        migrations.AddField(
            model_name='bill',
            name='order_payed',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='market.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Approving'), (1, 'Pending'), (2, 'Completed'), (3, 'Canceled')], default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_apply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.voucher'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('customer', 'store'), name='customer_order_store'),
        ),
    ]
