# Generated by Django 4.1 on 2022-08-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_rename_product_orderdetail_product_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
    ]
