# Generated by Django 4.1 on 2022-08-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_cartdetail_remove_order_order_shipper_option_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
