# Generated by Django 4.1 on 2022-08-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='customer_order_store',
        ),
    ]
