# Generated by Django 4.1 on 2022-08-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_remove_order_customer_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.option'),
        ),
    ]
