# Generated by Django 4.1 on 2022-09-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='code',
            field=models.TextField(default='nightowl'),
        ),
    ]
