# Generated by Django 4.1 on 2022-09-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
    ]
