# Generated by Django 4.1 on 2022-09-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_voucher_is_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.TextField(default='nightowl', unique=True),
        ),
    ]
