# Generated by Django 4.1 on 2022-09-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_orderdetail_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.TextField(default='ABC'),
        ),
    ]
