# Generated by Django 4.1 on 2022-09-20 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_alter_address_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='weight',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='option',
            name='width',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
