# Generated by Django 4.1 on 2022-09-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_alter_option_weight_alter_option_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
