# Generated by Django 4.1 on 2022-09-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_order_shipping_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='ward_id',
            field=models.CharField(max_length=255),
        ),
    ]
