# Generated by Django 4.1 on 2022-09-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_alter_address_ward_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='unit_in_stock',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
