# Generated by Django 4.1 on 2022-09-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_alter_option_unit_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.IntegerField(choices=[(0, 'COD'), (1, 'OnlinePayment')], default=0),
        ),
    ]
