# Generated by Django 4.1 on 2022-09-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0026_order_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping',
            new_name='payment_type',
        ),
    ]
