# Generated by Django 4.1 on 2022-09-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_alter_cartdetail_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
