# Generated by Django 4.1 on 2022-09-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_bill_payed_for_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payed_for_seller',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'COD'), (1, 'OnlinePaymentWithMomo'), (2, 'PaymentWithNightOwlAmount')], default=0),
        ),
    ]
