# Generated by Django 4.1 on 2022-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0034_alter_user_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
