# Generated by Django 4.1 on 2022-10-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0042_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='subject',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
