# Generated by Django 4.1 on 2022-11-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0046_alter_orderdetail_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='night_owl/product'),
        ),
    ]
